apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-nginx
spec:
  selector:
    matchLabels:
      app: simple-nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: simple-nginx
    spec:
      containers:
        - name: simple-nginx-fe
          image: dtr.eu.demo.mirantis.com/ayang-prod/simple-nginx:latest
          ports:
            - containerPort: 80
