4apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-nginx
spec:
  selector:
    matchLabels:
      app: simple-nginx
<<<<<<< HEAD
<<<<<<< HEAD
  replicas: 4
=======
  replicas: 3
>>>>>>> Increasing replicas of Nginx to 3.
=======
  replicas: 5
>>>>>>> Change replica count to 5.
  template:
    metadata:
      labels:
        app: simple-nginx
    spec:
      containers:
        - name: simple-nginx-fe
          image: ${REGISTRY_HOSTNAME}/${IMAGE_NAMESPACE}/${IMAGE_REPOSITORY}:${IMAGE_TAG}
          ports:
            - containerPort: 80
